base_locale: ja
data:
  read:
    - config/locales/activerecord/%{locale}.yml
    - config/locales/views/%{locale}.yml
    - config/locales/devise.en.yml
    - config/locales/devise.views.ja.yml
    - config/locales/en.yml
search:
  paths:
    - app
  exclude:
    - app/assets/images
    - app/assets/fonts
    - app/assets/videos
  strict: false
ignore:
  - will_paginate.*
  - validation.*
  - simple_form.*
  - devise.*
  - activerecord.*
  - date.*
  - datetime.*
  - errors.*
  - helpers.*
  - number.*
  - support.*
  - time.*