name: Auto Assign

on:
  workflow_dispatch:
  pull_request:
    types:
      - 'opened'
      - 'reopened'

jobs:
  call-workflow-passing-data:
    permissions:
      pull-requests: write
    uses: inoway46/random-assign/.github/workflows/random-assign.yml@main
    with:
      number: ${{ github.event.pull_request.number }}
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
