name: Auto Assign

on:
  pull_request_target:
    types: [opened, reopened]

jobs:
  if: ${{ toJSON(github.event.pull_request.assignees) == '[]' }}
  call-workflow-passing-data:
    permissions:
      contents: write
      issues: write
      repository-projects: write
      pull-requests: write
    uses: inoway46/random-assign/.github/workflows/random-assign.yml@main
    with:
      path: .github/CODEOWNERS
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
